/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.adb.personaapp.vista;
//package co.edu.usbbog.adb.personaapp.vista.Principal;


import co.edu.usbbog.adb.personaapp.controlador.logica.Gestion;
import co.edu.usbbog.adb.personaapp.controlador.persistencia.dao.UsuarioDao;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class Login extends JPanel{

    Principal pr;
    Gestion g;
    public Login(Principal principal) {
        g = new Gestion();
        this.pr= principal;
        initComponents();
        jRadioButtoncassandra.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gestor = new javax.swing.ButtonGroup();
        Login = new java.awt.Panel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldContrasenia = new javax.swing.JTextField();
        jRadioButtonregistrar = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonmariadb = new javax.swing.JRadioButton();
        jRadioButtoncassandra = new javax.swing.JRadioButton();
        jRadioButtoninicio = new java.awt.Button();

        Login.setBackground(new java.awt.Color(255, 135, 10));
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jRadioButtonregistrar.setLabel("Registrar");
        jRadioButtonregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonregistrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        gestor.add(jRadioButtonmariadb);
        jRadioButtonmariadb.setText("MariaDB");

        gestor.add(jRadioButtoncassandra);
        jRadioButtoncassandra.setText("Cassandra");

        jRadioButtoninicio.setLabel("Inicio");
        jRadioButtoninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtoninicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(54, 70, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LoginLayout.createSequentialGroup()
                                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(jTextFieldUsuario)))
                                .addGroup(LoginLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel3)))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(jRadioButtonregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(jRadioButtonmariadb)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jRadioButtoncassandra))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jRadioButtoninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonmariadb)
                    .addComponent(jRadioButtoncassandra))
                .addGap(26, 26, 26)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtoninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonregistrarActionPerformed
       registrar();
    }//GEN-LAST:event_jRadioButtonregistrarActionPerformed

    private void jRadioButtoninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtoninicioActionPerformed
        String userM=jTextFieldUsuario.getText();        
        inicio();
    }//GEN-LAST:event_jRadioButtoninicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Panel Login;
    private javax.swing.ButtonGroup gestor;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JRadioButton jRadioButtoncassandra;
    public java.awt.Button jRadioButtoninicio;
    public javax.swing.JRadioButton jRadioButtonmariadb;
    public java.awt.Button jRadioButtonregistrar;
    public static javax.swing.JTextField jTextFieldContrasenia;
    public static javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    private void registrar() {
        pr.deLoginARegistro(this);
    }

    private void inicio() {
        if(validar()){
            pr.deLoginAMenu(this); 
            
        }else{
            JOptionPane.showMessageDialog(this, "Error");
            limpiar();
        }        
    }

    private boolean validar() {
        if (jTextFieldUsuario.getText().equals("")) {
            return false;
        } else if (jTextFieldContrasenia.getText().equals("")) {
            return false;
        } else if (jRadioButtoncassandra.isSelected()) {
            pr.setSgdb("cassandra");
            return g.iniciarSesion("cassandra", jTextFieldUsuario.getText(), jTextFieldContrasenia.getText());
        } else if (jRadioButtonmariadb.isSelected()) {
            pr.setSgdb("maria");
            return g.iniciarSesion("maria", jTextFieldUsuario.getText(), jTextFieldContrasenia.getText());
        } else {
            return false;
        }
    }

    private void limpiar() {
        jTextFieldUsuario.setText("");
        jTextFieldContrasenia.setText("");
    }


    
}
