/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.adb.personaapp.vista;

import co.edu.usbbog.adb.personaapp.controlador.logica.Gestion;
import co.edu.usbbog.adb.personaapp.controlador.persistencia.dao.UsuarioDao;
import java.awt.BorderLayout;

/**
 *
 * @author Chokolate
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    
    Principal pr;
    public Menu(Principal principal) {
        this.pr= principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonmodificar = new java.awt.Button();
        jRadioButtoneliminar = new java.awt.Button();

        Menu.setBackground(new java.awt.Color(255, 102, 0));
        Menu.setForeground(new java.awt.Color(255, 102, 0));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Menu Usuario");

        jRadioButtonmodificar.setLabel("Actualizar datos");
        jRadioButtonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmodificarActionPerformed(evt);
            }
        });

        jRadioButtoneliminar.setLabel("Eliminar cuenta");
        jRadioButtoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtoneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jRadioButtoneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jRadioButtonmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(136, 136, 136))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtoneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtoneliminarActionPerformed
       
        String usuarioLogin=Login.jTextFieldUsuario.getText();
        if(pr.getSgdb().equals("maria")){
        Gestion ge =new Gestion();
        ge.BorrarUsuario(usuarioLogin);
        pr.deMenuALogin(this);
        }else if(pr.getSgdb().equals("cassandra")){
        UsuarioDao usuario = new UsuarioDao();
        usuario.eliminarUsuario(usuarioLogin);
        pr.deMenuALogin(this);
    }   
    }//GEN-LAST:event_jRadioButtoneliminarActionPerformed

    private void jRadioButtonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmodificarActionPerformed
        
        pr.deMenuAmodificar(this);
        
    }//GEN-LAST:event_jRadioButtonmodificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static java.awt.Panel Menu;
    public javax.swing.JLabel jLabel5;
    public java.awt.Button jRadioButtoneliminar;
    public java.awt.Button jRadioButtonmodificar;
    // End of variables declaration//GEN-END:variables
}
