/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.adb.personaapp.vista;

import co.edu.usbbog.adb.personaapp.controlador.logica.Gestion;
import co.edu.usbbog.adb.personaapp.controlador.persistencia.dao.ConexionCassandra;
import co.edu.usbbog.adb.personaapp.controlador.persistencia.dao.UsuarioDao;
import static co.edu.usbbog.adb.personaapp.vista.Login.jTextFieldContrasenia;
import static co.edu.usbbog.adb.personaapp.vista.Login.jTextFieldUsuario;

/**
 *
 * @author Chokolate
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    ConexionCassandra cassandra;
    Principal pr;
    public Registro(Principal principal) {
        this.pr= principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtoncassandra = new javax.swing.JRadioButton();
        gestion = new javax.swing.ButtonGroup();
        Registro = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonCancelar = new java.awt.Button();
        Apellido1 = new javax.swing.JLabel();
        jButtonGuardar = new java.awt.Button();
        jTextFieldTel1R = new javax.swing.JTextField();
        jTextFieldTel2R = new javax.swing.JTextField();
        jTextFieldContraseñaR = new javax.swing.JTextField();
        jTextFieldApellidoR = new javax.swing.JTextField();
        jTextFieldCorreo1R = new javax.swing.JTextField();
        jTextFieldCorreo2R = new javax.swing.JTextField();
        jTextFieldNombreR = new javax.swing.JTextField();
        jTextFieldUsuarioR = new javax.swing.JTextField();
        Edad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        genero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jRadioButtoncassandra2 = new javax.swing.JRadioButton();
        jRadioButtonmariadb2 = new javax.swing.JRadioButton();

        jRadioButtoncassandra.setText("Cassandra");

        Registro.setBackground(new java.awt.Color(255, 102, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Registro Usuario");

        jLabel6.setText("Nombre");

        jLabel7.setText("Usuario");

        jLabel8.setText("Contraseña");

        Apellido.setText("Apellido");

        jLabel10.setText("Telefono");

        jButtonCancelar.setActionCommand("Cancelar");
        jButtonCancelar.setLabel("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        Apellido1.setText("Correo");

        jButtonGuardar.setLabel("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTextFieldContraseñaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContraseñaRActionPerformed(evt);
            }
        });

        jTextFieldCorreo1R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreo1RActionPerformed(evt);
            }
        });

        jTextFieldUsuarioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioRActionPerformed(evt);
            }
        });

        Edad.setText("Edad");

        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });

        genero.setText("Genero");

        jTextFieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGeneroActionPerformed(evt);
            }
        });

        gestion.add(jRadioButtoncassandra2);
        jRadioButtoncassandra2.setText("Cassandra");

        gestion.add(jRadioButtonmariadb2);
        jRadioButtonmariadb2.setText("MariaDB");
        jRadioButtonmariadb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmariadb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro);
        Registro.setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(137, 137, 137))
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(RegistroLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(RegistroLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RegistroLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jTextFieldTel1R, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(RegistroLayout.createSequentialGroup()
                            .addComponent(Apellido1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCorreo1R, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RegistroLayout.createSequentialGroup()
                            .addComponent(Edad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RegistroLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RegistroLayout.createSequentialGroup()
                            .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(genero)
                                .addComponent(jLabel7))
                            .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(RegistroLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jTextFieldUsuarioR, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(RegistroLayout.createSequentialGroup()
                            .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(Apellido))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldApellidoR, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldContraseñaR, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jRadioButtonmariadb2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTel2R, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCorreo2R, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtoncassandra2))
                        .addGap(0, 122, Short.MAX_VALUE))))
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtoncassandra2)
                    .addComponent(jRadioButtonmariadb2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldUsuarioR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genero)
                    .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edad)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido1)
                    .addComponent(jTextFieldCorreo2R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCorreo1R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido)
                    .addComponent(jTextFieldApellidoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldContraseñaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTel2R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTel1R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldContraseñaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContraseñaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContraseñaRActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
        validar();
        pr.deRegistroALogin(this);
        /*
        UsuarioDao usuario =new UsuarioDao();
        usuario.insertarUsuario(jTextFieldNombreR.getText(), jTextFieldApellidoR.getText(), Integer.parseInt(jTextFieldEdad.getText()), jTextFieldTel1R.getText(), jTextFieldTel2R.getText(),jTextFieldCorreo1R.getText() , jTextFieldCorreo2R.getText(), jTextFieldGenero.getText(),jTextFieldUsuarioR.getText(),jTextFieldContraseñaR.getText());
        pr.deRegistroALogin(this);*/
      // Gestion.insertarUsuario(jTextFieldApellidoR.getText(), jTextFieldContraseñaR.getText(), jTextFieldGenero.getText(), jTextFieldNombreR.getText(), jTextFieldUsuarioR.getText(), Integer.parseInt(jTextFieldEdad.getText()), jTextFieldTel1R.getText(), jTextFieldTel2R.getText(), jTextFieldCorreo1R.getText(), jTextFieldCorreo2R.getText());
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        pr.deRegistroALogin(this);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldCorreo1RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreo1RActionPerformed

    }//GEN-LAST:event_jTextFieldCorreo1RActionPerformed

    private void jTextFieldUsuarioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioRActionPerformed

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadActionPerformed

    private void jTextFieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGeneroActionPerformed

    private void jRadioButtonmariadb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmariadb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonmariadb2ActionPerformed

 public void validar() {       
        if (jRadioButtoncassandra2.isSelected()) {
                    
            UsuarioDao usuario =new UsuarioDao();
        usuario.insertarUsuario(jTextFieldNombreR.getText(), jTextFieldApellidoR.getText(), Integer.parseInt(jTextFieldEdad.getText()), jTextFieldTel1R.getText(), jTextFieldTel2R.getText(),jTextFieldCorreo1R.getText() , jTextFieldCorreo2R.getText(), jTextFieldGenero.getText(),jTextFieldUsuarioR.getText(),jTextFieldContraseñaR.getText());
        pr.deRegistroALogin(this);
            
        } else if(jRadioButtonmariadb2.isSelected()) {
            
            Gestion.insertarUsuario(jTextFieldApellidoR.getText(), jTextFieldContraseñaR.getText(), jTextFieldGenero.getText(), jTextFieldNombreR.getText(), jTextFieldUsuarioR.getText(), Integer.parseInt(jTextFieldEdad.getText()), jTextFieldTel1R.getText(), jTextFieldTel2R.getText(), jTextFieldCorreo1R.getText(), jTextFieldCorreo2R.getText());
        
        }
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Apellido;
    public javax.swing.JLabel Apellido1;
    private javax.swing.JLabel Edad;
    private java.awt.Panel Registro;
    private javax.swing.JLabel genero;
    private javax.swing.ButtonGroup gestion;
    public java.awt.Button jButtonCancelar;
    public java.awt.Button jButtonGuardar;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JRadioButton jRadioButtoncassandra;
    public javax.swing.JRadioButton jRadioButtoncassandra2;
    public javax.swing.JRadioButton jRadioButtonmariadb2;
    public javax.swing.JTextField jTextFieldApellidoR;
    public javax.swing.JTextField jTextFieldContraseñaR;
    public javax.swing.JTextField jTextFieldCorreo1R;
    public javax.swing.JTextField jTextFieldCorreo2R;
    public javax.swing.JTextField jTextFieldEdad;
    public javax.swing.JTextField jTextFieldGenero;
    public javax.swing.JTextField jTextFieldNombreR;
    public javax.swing.JTextField jTextFieldTel1R;
    public javax.swing.JTextField jTextFieldTel2R;
    public javax.swing.JTextField jTextFieldUsuarioR;
    // End of variables declaration//GEN-END:variables

}
